class Conversion{
    constructor(category,convertTo,convertFrom,value){
        this.category = category;
        this.convertTo=convertTo;
        this.convertFrom=convertFrom;
        this.value=value;
        this.ConversionDict = {
            Length: {
                'pico': {
                    'picometer': 1e0,
                    'nanometer': 1e-3,
                    'micrometer': 1e-6,
                    'millimeter': 1e-9,
                    'centimeter': 1e-10,
                    'decimeter': 1e-11,
                    'meter': 1e-12,
                    'kilometer': 1e-15,
                    'inch': 3.937e-11,
                    'foot': 3.281e-12,
                    'yard': 1.094e-12,
                    'mile': 6.214e-16,
                },
                'nano': {
                    'picometer': 1e3,
                    'nanometer': 1e0,
                    'micrometer': 1e-3,
                    'millimeter': 1e-6,
                    'centimeter': 1e-7,
                    'decimeter': 1e-8,
                    'meter': 1e-9,
                    'kilometer': 1e-12,
                    'inch': 3.937e-8,
                    'foot': 3.281e-9,
                    'yard': 1.094e-9,
                    'mile': 6.214e-13,
                },
                'micro': {
                    'picometer': 1e6,
                    'nanometer': 1e3,
                    'micrometer': 1e0,
                    'millimeter': 1e-3,
                    'centimeter': 1e-4,
                    'decimeter': 1e-5,
                    'meter': 1e-6,
                    'kilometer': 1e-9,
                    'inch': 3.937e-5,
                    'foot': 3.281e-6,
                    'yard': 1.094e-6,
                    'mile': 6.214e-10,
                },
                'milli': {
                    'picometer': 1e9,
                    'nanometer': 1e6,
                    'micrometer': 1e3,
                    'millimeter': 1e0,
                    'centimeter': 1e-1,
                    'decimeter': 1e-2,
                    'meter': 1e-3,
                    'kilometer': 1e-6,
                    'inch': 3.937e-2,
                    'foot': 3.281e-3,
                    'yard': 1.094e-3,
                    'mile': 6.214e-7,
                },
                'centi': {
                    'picometer': 1e10,
                    'nanometer': 1e7,
                    'micrometer': 1e4,
                    'millimeter': 1e1,
                    'centimeter': 1e0,
                    'decimeter': 1e-1,
                    'meter': 1e-2,
                    'kilometer': 1e-5,
                    'inch': 3.937e-3,
                    'foot': 3.281e-2,
                    'yard': 1.094e-2,
                    'mile': 6.214e-6,
                },
                'deci': {
                    'picometer': 1e11,
                    'nanometer': 1e8,
                    'micrometer': 1e5,
                    'millimeter': 1e2,
                    'centimeter': 1e1,
                    'decimeter': 1e0,
                    'meter': 1e-1,
                    'kilometer': 1e-4,
                    'inch': 3.937e-2,
                    'foot': 3.281e-1,
                    'yard': 1.094e-1,
                    'mile': 6.214e-5,
                },
                'meter': {
                    'picometer': 1e12,
                    'nanometer': 1e9,
                    'micrometer': 1e6,
                    'millimeter': 1e3,
                    'centimeter': 1e2,
                    'decimeter': 1e1,
                    'meter': 1e0,
                    'kilometer': 1e-3,
                    'inch': 3.937e-1,
                    'foot': 3.281e0,
                    'yard': 1.094e0,
                    'mile': 6.214e-4,
                },
                'kilometer': {
                    'picometer': 1e15,
                    'nanometer': 1e12,
                    'micrometer': 1e9,
                    'millimeter': 1e6,
                    'centimeter': 1e5,
                    'decimeter': 1e4,
                    'meter': 1e3,
                    'kilometer': 1e0,
                    'inch': 3.937e3,
                    'foot': 3.281e3,
                    'yard': 1.094e3,
                    'mile': 6.214e-1,
                },
                'inch': {
                    'picometer': 2.54e10,
                    'nanometer': 2.54e7,
                    'micrometer': 2.54e4,
                    'millimeter': 2.54e1,
                    'centimeter': 2.54e0,
                    'decimeter': 2.54e-1,
                    'meter': 2.54e-2,
                    'kilometer': 2.54e-5,
                    'inch': 1e0,
                    'foot': 8.33e-2,
                    'yard': 2.78e-2,
                    'mile': 1.58e-5,
                },
                'foot': {
                    'picometer': 3.05e11,
                    'nanometer': 3.05e8,
                    'micrometer': 3.05e5,
                    'millimeter': 3.05e2,
                    'centimeter': 3.05e1,
                    'decimeter': 3.05e0,
                    'meter': 3.05e-1,
                    'kilometer': 3.05e-4,
                    'inch': 1.2e1,
                    'foot': 1e0,
                    'yard': 3.33e-1,
                    'mile': 1.89e-4,
                },
                'yard': {
                    'picometer': 9.14e11,
                    'nanometer': 9.14e8,
                    'micrometer': 9.14e5,
                    'millimeter': 9.14e2,
                    'centimeter': 9.14e1,
                    'decimeter': 9.14e0,
                    'meter': 9.14e-1,
                    'kilometer': 9.14e-4,
                    'inch': 3.6e1,
                    'foot': 3e0,
                    'yard': 1e0,
                    'mile': 5.68e-4,
                },
                'mile': {
                    'picometer': 1.61e15,
                    'nanometer': 1.61e12,
                    'micrometer': 1.61e9,
                    'millimeter': 1.61e6,
                    'centimeter': 1.61e5,
                    'decimeter': 1.61e4,
                    'meter': 1.61e3,
                    'kilometer': 1.61e0,
                    'inch': 6.34e4,
                    'foot': 5.28e3,
                    'yard': 1.76e3,
                    'mile': 1e0,
                },
            }
        }
    }

    convert() {
        return value * this.conversions[this.category][this.convertFrom][this.convertTo];
    }
}